# Generated by Django 5.1.3 on 2025-02-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='vivienda',
            field=models.FileField(blank=True, null=True, upload_to='vivienda'),
        ),
    ]
