# Generated by Django 5.1.3 on 2025-02-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_vivienda_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='proyecto',
            field=models.FileField(blank=True, null=True, upload_to='proyecto'),
        ),
    ]
