# Generated by Django 5.1.3 on 2025-02-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_proyecto_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='proyecto',
            new_name='foto',
        ),
    ]
