# Generated by Django 5.1.3 on 2025-02-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_rename_proyecto_proyecto_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vivienda',
            old_name='vivienda',
            new_name='foto',
        ),
    ]
